apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-freqmine
  labels:
    name: pasec-freqmine
spec:
  template:
    spec: 
      nodeSelector:
        nodelabel: A
      containers:
      - image: anakli/parsec:freqmine-native-reduced
        name: parsecfreqmine
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/parsecmgmt -a run -p freqmine -i native -n 8"]
      restartPolicy: Never
