apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-canneal
  labels:
    name: pasec-canneal
spec:
  template:
    spec: 
      nodeSelector:
        nodelabel: A
      containers:
      - image: anakli/parsec:canneal-native-reduced
        name: parseccanneal
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/parsecmgmt -a run -p canneal -i native -n 8"]
      restartPolicy: Never
